<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>centerDPO-Litvin</AssemblyName>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>centerDPO</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
</Project>
